sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7zUcuTtgcPUEBWQ1yn
    access-key-secret: gUSfmXt5V4vpZCqIgRSMZFJlW3ylr0
    bucket-name: sky-iliuziang
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10